# Generated by Django 4.2.1 on 2023-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytexture',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entitytexture',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
